// ─── Enemy support options for dropdown ──────────────────────────────────────

export const ENEMY_SUPPORTS = [
    "Unknown",
    // engage / hook
    "Leona",
    "Nautilus",
    "Blitzcrank",
    "Alistar",
    "Rell",
    "Thresh",
    "Pyke",
    "Rakan",
    "Pantheon",
    "Poppy",
    "Elise",
    "Fiddlesticks",
    "Galio",
    "Shaco",
    "Shen",
    "Tahm Kench",
    "Taric",
    "Braum",
    // poke / mage
    "Vel'Koz",
    "Xerath",
    "Zyra",
    "Lux",
    "Brand",
    "Zoe",
    "Neeko",
    "LeBlanc",
    "Anivia",
    "Mel",
    // enchanter
    "Soraka",
    "Sona",
    "Nami",
    "Milio",
    "Lulu",
    "Janna",
    "Yuumi",
    "Karma",
    "Seraphine",
    "Zilean",
    "Renata Glasc",
    // utility / hybrid
    "Maokai",
    "Morgana",
    "Senna",
    "Bard",
    "Swain",
] as const;

// ─── Ally ADC options for dropdown ──────────────────────────────────────────

export const ALLY_ADCS = [
    "Unknown",
    // hypercarries / on-hit
    "KogMaw",
    "Vayne",
    "Twitch",
    "Jinx",
    "Zeri",
    "Aphelios",
    "Yunara",
    "Smolder",
    // poke / range
    "Caitlyn",
    "Ezreal",
    "Jhin",
    "Varus",
    "Ziggs",
    "Vel'Koz",
    "Corki",
    // all-in / aggressive
    "Draven",
    "Samira",
    "Lucian",
    "Kalista",
    "Nilah",
    "Tristana",
    // utility / flex
    "MissFortune",
    "Sivir",
    "Ashe",
    "Xayah",
    "Kai'Sa",
    "Senna",
    // scaling mages in bot
    "Mel",
    "Brand",
    "Seraphine",
    "Swain",
    "Karthus",
    "Vladimir",
    "Veigar",
    "Aurelion Sol",
    "Yasuo",
] as const;
